### ISSUE TITLE
ValueError when set the score to "max-logit"

### ISSUE THREAD

**Issue by X1AOX1A** [deeplearning-wisc/MCM#17]
When set the score to "max-logit", it will raise the ValueError:

Bash file: 

```
EXP_NAME=eval_ood
ID=ImageNet100
SCORE=max-logit
CKPT=ViT-B/16
DATA_ROOT=path/to/data/root

python eval_ood_detection.py --in_dataset ${ID} --name ${EXP_NAME} --CLIP_ckpt ${CKPT} --score ${SCORE} --root-dir ${DATA_ROOT}
```

Error information:

```
2024-01-21 14:12:33,795 : #########eval_ood############
100%|█████████████████████████████████████████████████████████████████████| 10/10 [00:10<00:00,  1.07s/it]
Traceback (most recent call last):
  File "/data/DEMOS/MCM/eval_ood_detection.py", line 103, in <module>
    main()
  File "/data/DEMOS/MCM/eval_ood_detection.py", line 81, in main
    in_score  = get_ood_scores_clip(args, net, test_loader, test_labels, in_dist=True)
  File "/data/DEMOS/MCM/utils/detection_util.py", line 249, in get_ood_scores_clip
    return concat(_score)[:len(loader.dataset)].copy()   
  File "/data/DEMOS/MCM/utils/detection_util.py", line 214, in <lambda>
    concat = lambda x: np.concatenate(x, axis=0)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by alvinmingsf** [comment]
Thanks for pointing out! Just added support for the `max-logit` score. Please see L233 & L247 in utils/detection_util.py. 
`if args.score == 'max-logit': smax = to_np(output)`

**Comment by X1AOX1A** [comment]
Thank you for your prompt response!
